# Generated by Django 3.1.2 on 2020-11-04 02:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
